version: '3.8'
#использовать определенную версию Compose file
services:
#определяет какие сервисы должны быть запущены
  db:
  #название сервиса
    #используемый образ
    image: postgres:latest
    
    # secrets:
    #    - db-password
    ports:
      - 5434:5432
      #порт хоста : порт контейнера
    environment:
    #переменные среды
      POSTGRES_USER: 'denis'
      POSTGRES_PASSWORD: '000111'
      POSTGRES_DB: 'taxi'
    volumes:
      - /home/denis/Projects/1t/taxi_analyse/db_data:/etc/data
      #определение скрипта данных
      - ./sql_scripts/create_table.sql:/docker-entrypoint-initdb.d/create_table.sql
      - ./sql_scripts/sql_task.sql:/docker-entrypoint-initdb.d/sql_task.sql
      #определение хранилища для запуска при создании контейнера
      #- /myvolume:/var/lib/postgresql/data

    healthcheck:
    #проверка состояния контейнера
      test: ["CMD", "pg_isready", "-U", "denis", "000111"]
      interval: 5s
      timeout: 30s
      retries: 5
    restart: always
# secrets:
#   db-password:
#     file: db/password.txt 
